-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.
-- Hypertable conversions and continuous aggregates. Sorts last so the tables Prisma
-- created in its own migrations already exist. All DDL is idempotent (constraint 3).

-- Hypertable: SensorReading
SELECT create_hypertable(
  '"SensorReading"',
  by_range('time', INTERVAL '1 day'),
  if_not_exists => TRUE,
  migrate_data  => TRUE
);

-- Retention policy: SensorReading
SELECT add_retention_policy('"SensorReading"', drop_after => INTERVAL '90 days', if_not_exists => TRUE);

-- Compression (columnstore) policy: SensorReading
ALTER TABLE "SensorReading" SET (
  timescaledb.enable_columnstore = true,
  timescaledb.segmentby = '"sensorId"',
  timescaledb.orderby = '"time" DESC'
);
CALL add_columnstore_policy('"SensorReading"', after => INTERVAL '7 days', if_not_exists => TRUE);

-- Continuous aggregate: SensorReadingHourly
CREATE MATERIALIZED VIEW IF NOT EXISTS "SensorReadingHourly"
  WITH (timescaledb.continuous) AS
SELECT
  time_bucket('1 hour', "time") AS "bucket",
  "sensorId" AS "sensorId",
  avg("value") AS "avgValue",
  min("value") AS "minValue",
  max("value") AS "maxValue",
  count("value") AS "samples"
FROM "SensorReading"
GROUP BY "bucket", "sensorId"
WITH NO DATA;

SELECT add_continuous_aggregate_policy('"SensorReadingHourly"',
  start_offset      => INTERVAL '7 days',
  end_offset        => INTERVAL '1 hour',
  schedule_interval => INTERVAL '1 hour',
  if_not_exists     => TRUE
);
