-- AUTO-GENERATED by prisma-extension-timescaledb. Do not edit by hand.
-- TimescaleDB extension setup. Standalone & leading so it runs before any table or
-- hypertable DDL (CLAUDE.md constraint 1).
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
