query HypertableStats($model: HypertableModel!) {
  hypertableStats(model: $model) {
    approximateRowCount
    totalBytes
    tableBytes
    indexBytes
    toastBytes
    totalChunks
    compressedChunks
    beforeCompressionBytes
    afterCompressionBytes
  }
}
